version: "3.11"
services:
  litellm:
    build:
      context: .
      dockerfile: Dockerfile.mine.2
      args:
        target: runtime
    image: ghcr.io/berriai/litellm:${DOCKER_TAG:-main-latest}
    ports:
      - "${LITELLM_PORT:-4000}:4000"
    volumes:
      - litellm-config:/app/config
    environment:
      DATABASE_URL: "postgresql://postgres:${DB_PASSWORD:-example}@db:5432/postgres"
      STORE_MODEL_IN_DB: "${STORE_MODEL_IN_DB:-True}"
      store_model_in_db: "${store_model_in_db:-True}"
      AZURE_API_KEY: "${AZURE_API_KEY}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      REPLICATE_API_KEY: "${REPLICATE_API_KEY}"
      ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
      TOGETHERAI_API_KEY: "${TOGETHERAI_API_KEY}"
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
      UI_USERNAME: "${UI_USERNAME}"
      UI_PASSWORD: "${UI_PASSWORD}"
      PROXY_ADMIN_ID: "${PROXY_ADMIN_ID}"
      ALLOW_USER_AUTH: "${ALLOW_USER_AUTH:-true}"
      UI_ACCESS_MODE: "${UI_ACCESS_MODE}"
      SSO_MODE: "${SSO_MODE:-false}"
      AUTH_MODE: "${AUTH_MODE}"
      LOGIN_MODE: "${LOGIN_MODE}"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "${REDIS_PASSWORD:-your_redis_password}"
    restart: unless-stopped
    depends_on:
      - db
      - redis

  db:
    image: postgres
    ports:
      - "6656:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD:-example}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-your_redis_password}
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  litellm-config:
  db-data:
  redis-data:
