version: "3.11"
services:
  litellm:
    build:
      context: .
      dockerfile: Dockerfile.mine.2
      args:
        target: runtime
    image: ghcr.io/berriai/litellm:${DOCKER_TAG:-main-latest}
    ports:
      - "${LITELLM_PORT:-4000}:4000"
    volumes:
      - litellm-config:/app/config
    environment:
      DATABASE_URL: "postgresql://postgres:${DB_PASSWORD:-example}@db:5432/postgres"
      STORE_MODEL_IN_DB: "${STORE_MODEL_IN_DB:-True}"
      AZURE_API_KEY: "${AZURE_API_KEY}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      REPLICATE_API_KEY: "${REPLICATE_API_KEY}"
      ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
      TOGETHERAI_API_KEY: "${TOGETHERAI_API_KEY}"
    #env_file:
      #- .env
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD:-example}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  litellm-config:
  db-data:
