version: "3.11"
services:
  litellm:
    build:
      context: .
      dockerfile: Dockerfile.mine
      args:
        target: runtime
    image: ghcr.io/berriai/litellm:main-stable
    ports:
      - "${LITELLM_PORT:-4000}:4000"
    volumes:
      - ./config:/app/config
    #command: ["--config", "/app/config/config.yaml", "--port", "${LITELLM_PORT:-4000}", "--num_workers", "${NUM_WORKERS:-8}"]  
    environment:
      DATABASE_URL: "postgresql://postgres:${DB_PASSWORD:-example}@db:5432/postgres"
      STORE_MODEL_IN_DB: "${STORE_MODEL_IN_DB:-True}"
      #LANGFUSE_HOST: "${LANGFUSE_HOST}"
      #LANGFUSE_PUBLIC_KEY: "${LANGFUSE_PUBLIC_KEY}"
      #LANGFUSE_SECRET_KEY: "${LANGFUSE_SECRET_KEY}"
      AZURE_API_KEY: "{AZURE_API_KEY}"
      OPENAI_API_KEY: "{OPENAI_API_KEY}"
      REPLICATE_API_KEY: "{REPLICATE_API_KEY}"
      ANTHROPIC_API_KEY: "{ANTHROPIC_API_KEY}"
      TOGETHERAI_API_KEY: "{TOGETHERAI_API_KEY}"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD:-example}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
